# Generated by Django 4.1 on 2022-08-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
